name: Deploy Cloud Functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI Nativo
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install
        working-directory: ./fretemax-projeto-final/functions

      - name: Autenticar e Fazer Deploy
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_key.json
          firebase deploy --only functions --project fretemax-4b257 --force
        working-directory: ./fretemax-projeto-final
